# Generated by Django 5.1.4 on 2024-12-11 11:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('squat', models.CharField(max_length=100)),
                ('benchpress', models.CharField(max_length=100)),
                ('deadlift', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubTrainingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('set_number', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('rep_number', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtrainings', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtrainings', to='training.trainingmodel')),
            ],
        ),
    ]
