# Generated by Django 5.1.4 on 2024-12-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtrainingmodel',
            old_name='training',
            new_name='training_id',
        ),
    ]
