# Generated by Django 5.1.4 on 2024-12-12 03:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_rename_training_id_subtrainingmodel_training'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTrainingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True)),
                ('set_number', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('rep_number', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)])),
                ('rm', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintrainings', to='training.trainingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintrainings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
