# Generated by Django 5.1.4 on 2024-12-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_maintrainingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmodel',
            name='benchpress',
        ),
        migrations.RemoveField(
            model_name='trainingmodel',
            name='deadlift',
        ),
        migrations.RemoveField(
            model_name='trainingmodel',
            name='squat',
        ),
    ]
