# Generated by Django 5.1.4 on 2024-12-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_remove_trainingmodel_benchpress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtrainingmodel',
            name='weight',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
