# Generated by Django 5.1.4 on 2024-12-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_subtrainingmodel_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtrainingmodel',
            name='weight',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
