# Generated by Django 5.1.4 on 2024-12-16 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_maintrainingmodel_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
