# Generated by Django 5.1.4 on 2024-12-17 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_trainingmodel_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtraining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.subtrainingmodel')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'training', 'subtraining')},
            },
        ),
    ]
