# Generated by Django 5.1.4 on 2024-12-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auxiliary'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtrainingmodel',
            name='help_training',
            field=models.BooleanField(default=False),
        ),
    ]
