# Generated by Django 5.1.4 on 2024-12-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_subtrainingmodel_total_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintrainingmodel',
            name='total_weight',
            field=models.FloatField(default=0.0, verbose_name='合計重量'),
        ),
    ]
