# Generated by Django 5.1.4 on 2024-12-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(default='未設定', max_length=100, verbose_name='所属'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default='2020-01-01', verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(None, '--'), ('m', '男性'), ('f', '女性')], default=None, max_length=1, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=170, verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_score',
            field=models.IntegerField(default=500, verbose_name='合計重量'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=70, verbose_name='体重'),
        ),
    ]
