# Generated by Django 5.1.4 on 2024-12-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_affiliation_alter_profile_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gl_point',
            field=models.FloatField(default=0.0, verbose_name='GLポイント'),
        ),
    ]
