# Generated by Django 5.1.4 on 2024-12-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_gl_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(None, '--'), ('m', '男性'), ('f', '女性')], default='m', max_length=1, verbose_name='性別'),
        ),
    ]
